export const ANALYTICS_EVENTS = {
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_COMPARE: 'PRODUCT_COMPARE',
  PRODUCT_WISHLIST: 'PRODUCT_WISHLIST',
  PRODUCT_SHARE: 'PRODUCT_SHARE',
  PRODUCT_CLICK: 'PRODUCT_CLICK',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
  PRODUCT_PURCHASE: 'PRODUCT_PURCHASE',
  PRODUCT_REVIEW: 'PRODUCT_REVIEW',
  PRODUCT_REPORT: 'PRODUCT_REPORT',
  SELLER_PROFILE_VIEW: 'SELLER_PROFILE_VIEW',
  SELLER_FOLLOW: 'SELLER_FOLLOW',
  STORE_VISIT: 'STORE_VISIT',
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  BRAND_VIEW: 'BRAND_VIEW',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  SEARCH: 'SEARCH',
  FILTER: 'FILTER',
  NOTIFICATION_CLICK: 'NOTIFICATION_CLICK',
} as const;

export type AnalyticsEventType = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

export const ANALYTICS_EVENT_VALUES = Object.values(ANALYTICS_EVENTS);

export function isAnalyticsEventType(value: unknown): value is AnalyticsEventType {
  return typeof value === 'string' && ANALYTICS_EVENT_VALUES.includes(value as AnalyticsEventType);
}
