export const ANALYTICS_EVENTS = {
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_COMPARE: 'PRODUCT_COMPARE',
  PRODUCT_WISHLIST: 'PRODUCT_WISHLIST',
  PRODUCT_SHARE: 'PRODUCT_SHARE',
  PRODUCT_CLICK: 'PRODUCT_CLICK',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
  PRODUCT_PURCHASE: 'PRODUCT_PURCHASE',
  PRODUCT_REVIEW: 'PRODUCT_REVIEW',
  PRODUCT_REPORT: 'PRODUCT_REPORT',
  SELLER_PROFILE_VIEW: 'SELLER_PROFILE_VIEW',
  SELLER_FOLLOW: 'SELLER_FOLLOW',
  STORE_VISIT: 'STORE_VISIT',
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  BRAND_VIEW: 'BRAND_VIEW',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  SEARCH: 'SEARCH',
  FILTER: 'FILTER',
  NOTIFICATION_CLICK: 'NOTIFICATION_CLICK',
  SELLER_VERIFIED: 'SELLER_VERIFIED',
  SELLER_REJECTED: 'SELLER_REJECTED',
  PRODUCT_APPROVED: 'PRODUCT_APPROVED',
  PRODUCT_REJECTED: 'PRODUCT_REJECTED',
  REPORT_RESOLVED: 'REPORT_RESOLVED',
  REPORT_CREATED: 'REPORT_CREATED',
  SEARCH_CLICK: 'SEARCH_CLICK',
  SEARCH_NO_RESULT: 'SEARCH_NO_RESULT',
  SEARCH_AUTOCOMPLETE_SELECT: 'SEARCH_AUTOCOMPLETE_SELECT',
  SEARCH_SUGGESTION_SELECT: 'SEARCH_SUGGESTION_SELECT',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_DISMISSED: 'NOTIFICATION_DISMISSED',
  BROADCAST_SENT: 'BROADCAST_SENT',
  EMAIL_OPEN: 'EMAIL_OPEN',
  PUSH_OPEN: 'PUSH_OPEN',
} as const;

export type AnalyticsEventType = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

export const ANALYTICS_EVENT_VALUES = Object.values(ANALYTICS_EVENTS);

export function isAnalyticsEventType(value: unknown): value is AnalyticsEventType {
  return typeof value === 'string' && ANALYTICS_EVENT_VALUES.includes(value as AnalyticsEventType);
}
