import type { CatalogBrandPost } from './catalogTypes';

const nowIso = () => new Date().toISOString();

export const defaultBrandPosts = (): CatalogBrandPost[] => {
  const ts = nowIso();
  return [
    {
      id: 'bp-1',
      slug: 'aarong-eid-carnival-2026',
      brandId: '10',
      brandName: 'Aarong',
      brandLogo: 'Aa',
      kind: 'festival',
      title: 'Aarong Eid Carnival 2026 — Heritage Collection Preview',
      excerpt:
        'Experience handcrafted Eid collections, live artisan demos, and exclusive early access to limited festive pieces across Dhaka outlets.',
      heroImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1200&h=700&fit=crop',
      bannerImages: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1920&h=800&fit=crop',
        'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1920&h=800&fit=crop',
      ],
      body: [
        'Aarong invites you to the Eid Carnival 2026 — a celebration of Bangladeshi craftsmanship with curated heritage collections, trunk shows, and live weaving demonstrations.',
        'Visit participating outlets in Gulshan, Dhanmondi, and Bashundhara City for styling sessions, gift wrapping, and members-only preview hours before the public launch.',
        'Sponsored brand awareness post. Product availability varies by outlet. Terms apply.',
      ],
      startDate: '2026-04-10T10:00:00',
      endDate: '2026-04-20T22:00:00',
      location: 'Multiple Aarong outlets · Dhaka',
      ctaLabel: 'Find nearest outlet',
      ctaUrl: '/brands/10',
      linkedProductIds: ['5', '6'],
      sponsored: true,
      status: 'live',
      publishedAt: '2026-03-28',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-2',
      slug: 'sailor-summer-drop-preview',
      brandId: '12',
      brandName: 'Sailor',
      brandLogo: 'Sa',
      kind: 'launch',
      title: 'Sailor Summer Drop — Linen & Resort Line Preview',
      excerpt:
        "First look at Sailor's breathable linen shirts and resort polos. Notify-me slots open for verified Choosify shoppers.",
      heroImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&h=700&fit=crop',
      body: [
        "Sailor's Summer Drop focuses on lightweight linen blends engineered for Bangladesh's heat — wrinkle-resistant finishes and expanded tall sizing.",
        'Preview pieces will appear in select stores from April 1. Choosify users can save the drop to their dashboard for restock alerts.',
      ],
      startDate: '2026-04-01T09:00:00',
      endDate: '2026-06-30T23:59:00',
      location: 'Nationwide Sailor stores',
      ctaLabel: 'View brand profile',
      ctaUrl: '/brands/12',
      sponsored: true,
      status: 'live',
      publishedAt: '2026-03-25',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-3',
      slug: 'yellow-dhaka-fashion-week-styling',
      brandId: '11',
      brandName: 'Yellow',
      brandLogo: 'Y',
      kind: 'event',
      title: 'Yellow × Dhaka Fashion Week — Styling Lounge',
      excerpt:
        'Book a 15-minute styling session with Yellow consultants during Dhaka Fashion Week. Limited daily slots.',
      heroImage: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&h=700&fit=crop',
      body: [
        'Yellow hosts an on-site styling lounge at Dhaka Fashion Week with complimentary fit checks and accessory pairing for registered guests.',
        'Walk-ins welcome after 4 PM subject to availability. Sponsored event listing by Yellow.',
      ],
      startDate: '2026-05-05T11:00:00',
      endDate: '2026-05-08T21:00:00',
      location: 'ICCB, Dhaka',
      ctaLabel: 'Explore Yellow',
      ctaUrl: '/brands/11',
      sponsored: true,
      status: 'scheduled',
      publishedAt: '2026-03-20',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-4',
      slug: 'star-tech-gaming-fest',
      brandId: '15',
      brandName: 'Star Tech',
      brandLogo: 'ST',
      kind: 'event',
      title: 'Star Tech Gaming Fest — Builds, Demos & Bundle Deals',
      excerpt:
        'Hands-on RTX demo stations, custom PC build consults, and fest-only bundle pricing on peripherals.',
      heroImage: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=1200&h=700&fit=crop',
      body: [
        'Star Tech Gaming Fest returns with live benchmark demos, peripheral try-before-you-buy zones, and certified technician Q&A sessions.',
        'Fest bundles are valid in-store during event hours only. Sponsored post — prices confirmed at checkout.',
      ],
      startDate: '2026-04-18T12:00:00',
      endDate: '2026-04-19T20:00:00',
      location: 'Star Tech · IDB Bhaban & Multiplan',
      ctaLabel: 'See Star Tech deals',
      ctaUrl: '/brands/15',
      linkedProductIds: ['1', '2', '3'],
      sponsored: true,
      status: 'live',
      publishedAt: '2026-03-22',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-5',
      slug: 'apex-marathon-collab',
      brandId: '3',
      brandName: 'Apex',
      brandLogo: 'Ap',
      kind: 'campaign',
      title: 'Apex × City Marathon — Performance Runner Preview',
      excerpt:
        'Meet the upcoming Apex endurance runner developed with local athletes. Test pairs at the marathon expo zone.',
      heroImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=700&fit=crop',
      body: [
        'Apex showcases a marathon-focused silhouette with upgraded midsole foam and reflective upper panels at the city marathon expo.',
        'Limited tester sizes available — first come, first served. Sponsored campaign by Apex Footwear.',
      ],
      startDate: '2026-05-12T08:00:00',
      endDate: '2026-05-12T18:00:00',
      location: 'Hatirjheel Expo Ground',
      ctaLabel: 'Visit Apex brand page',
      ctaUrl: '/brands/3',
      sponsored: true,
      status: 'scheduled',
      publishedAt: '2026-03-18',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-6',
      slug: 'bata-back-to-school',
      brandId: '4',
      brandName: 'Bata',
      brandLogo: 'B',
      kind: 'campaign',
      title: 'Bata Back-to-School — Family Fit Day',
      excerpt:
        'Free foot measurement for kids, school shoe bundles, and same-day insole fitting at participating Bata stores.',
      heroImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&h=700&fit=crop',
      body: [
        "Bata's Back-to-School campaign offers bundled pricing on verified school shoes with extended exchange windows through May.",
        'Family Fit Day events run every Saturday morning at flagship locations.',
      ],
      startDate: '2026-04-05T09:00:00',
      endDate: '2026-05-31T20:00:00',
      location: 'Bata flagship stores',
      ctaLabel: 'Browse Bata',
      ctaUrl: '/brands/4',
      sponsored: true,
      status: 'live',
      publishedAt: '2026-03-15',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-7',
      slug: 'perfume-world-ramadan-gifting',
      brandId: '8',
      brandName: 'Perfume World',
      brandLogo: 'PW',
      kind: 'store_moment',
      title: 'Perfume World — Ramadan Gifting Atelier',
      excerpt: 'Curated gift sets, engraving, and concierge fragrance matching for Eid gifting.',
      heroImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=1200&h=700&fit=crop',
      body: [
        'Perfume World opens a seasonal gifting atelier with complimentary wrapping and scent profiling sessions.',
        'Appointment slots recommended on weekends. Sponsored store moment listing.',
      ],
      startDate: '2026-03-20T10:00:00',
      endDate: '2026-04-15T21:00:00',
      location: 'Banani & Gulshan branches',
      ctaLabel: 'View Perfume World',
      ctaUrl: '/brands/8',
      sponsored: true,
      status: 'live',
      publishedAt: '2026-03-10',
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'bp-8',
      slug: 'samsung-galaxy-unpacked-bd',
      brandId: '1',
      brandName: 'Samsung',
      brandLogo: 'S',
      kind: 'launch',
      title: 'Samsung Galaxy Unpacked — Bangladesh Watch Party',
      excerpt: 'Join authorized Samsung partners for the global Unpacked livestream with pre-order incentives.',
      heroImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&h=700&fit=crop',
      bannerImages: [
        'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1920&h=800&fit=crop',
        'https://images.unsplash.com/photo-1610945415295-d9bbfbe99f95?w=1920&h=800&fit=crop',
        'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=1920&h=800&fit=crop',
      ],
      body: [
        'Authorized Samsung outlets host watch parties with live Q&A, trade-in assessments, and pre-order bundles for Choosify-verified shoppers.',
        'Registration opens one week before the event. Sponsored launch awareness by Samsung.',
      ],
      startDate: '2026-07-15T19:00:00',
      endDate: '2026-07-15T23:00:00',
      location: 'Authorized Samsung stores · Dhaka & Chittagong',
      ctaLabel: 'Explore Samsung',
      ctaUrl: '/brands/1',
      linkedProductIds: ['1'],
      sponsored: true,
      status: 'scheduled',
      publishedAt: '2026-03-01',
      createdAt: ts,
      updatedAt: ts,
    },
  ];
};
