import { Address, Contact, CourierInfo } from './courier';

export type ShipmentStatus = 
  | 'pending_pickup'
  | 'picked_up'
  | 'in_transit'
  | 'delivered'
  | 'failed_delivery'
  | 'returned'
  | 'cancelled';

export interface PackageContent {
  productId: string;
  name: string;
  quantity: number;
  price: number;
}

export interface TrackingEvent {
  id: string;
  timestamp: string;
  status: string;
  location: string;
  description: string;
  remarks?: string;
  courierReference?: string;
}

export interface Location {
  city: string;
  district: string;
  lat?: number;
  lng?: number;
}

export interface Shipment {
  id: string;
  orderId: string;
  sellerId: string;
  customerId: string;
  
  status: ShipmentStatus;
  courier: CourierInfo;
  trackingNumber: string;
  waybillNumber?: string;
  
  pickupAddress: Address;
  deliveryAddress: Address;
  returnAddress?: Address;
  
  weight: number; // kg
  dimensions?: { length: number; width: number; height: number }; // cm
  packageType: 'regular' | 'express' | 'fragile' | 'perishable';
  contents: PackageContent[];
  
  codAmount: number;
  deliveryCharge: number;
  insuranceAmount?: number;
  totalCharge: number;
  
  createdAt: string;
  updatedAt: string;
  pickupScheduledAt?: string;
  pickedUpAt?: string;
  deliveredAt?: string;
  estimatedDeliveryAt?: string;
  
  trackingEvents: TrackingEvent[];
  currentLocation?: Location;
  
  sellerContact: Contact;
  customerContact: Contact;
  
  ruleName?: string;
  autoGeneratedLabel: boolean;
  autoRequestedPickup: boolean;
}
