import type { OpsShipment } from '../../../services/operationsApi';
import type { Shipment } from '../../../types/shipment';

/**
 * Sprint 11 remediation: ShipmentConsole and TrackingCenter were built against
 * the richer `Shipment` display type (src/types/shipment.ts) designed for the
 * fabricated Firestore/localStorage LogisticsService layer. The real backend
 * (server/operations/shipmentStore.ts, via GET/PATCH /operations/shipments)
 * only tracks the fields on `OpsShipment` — it has no concept of pickup
 * address, package weight/contents, or seller contact details.
 *
 * This maps the real record onto the display shape those two screens already
 * render, using fixed platform-level placeholders (not synthesized/random
 * data) for the fields the backend doesn't track yet.
 */
export function mapOpsShipmentToShipment(row: OpsShipment): Shipment {
  return {
    id: row.id,
    orderId: row.orderId,
    sellerId: 'platform',
    customerId: row.buyerId,
    status: row.status,
    courier: { code: row.courier, name: row.courier },
    trackingNumber: row.trackingNumber,
    pickupAddress: {
      street: 'Choosify Warehouse',
      city: 'Dhaka',
      district: 'Dhaka',
      postalCode: '1200',
      phone: '+8801700000000',
    },
    deliveryAddress: {
      street: row.deliveryAddress,
      city: row.region,
      district: row.region,
      postalCode: '1200',
      phone: row.recipientPhone,
    },
    weight: 1,
    packageType: 'regular',
    contents: [],
    codAmount: row.codAmount,
    deliveryCharge: row.deliveryCharge,
    totalCharge: row.deliveryCharge,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    trackingEvents: row.trackingEvents.map((evt) => ({
      id: evt.id,
      timestamp: evt.timestamp,
      status: evt.status,
      location: evt.location,
      description: evt.description,
    })),
    sellerContact: { name: 'Choosify', phone: '+880', email: 'ops@choosify.bd' },
    customerContact: { name: row.recipientName, phone: row.recipientPhone, email: '' },
    // Neither is real yet — no auto-label or auto-pickup flow exists server-side.
    autoGeneratedLabel: false,
    autoRequestedPickup: false,
  };
}
