/** Auto-extracted mock data from Choosify Admin CMS standalone HTML */
/* eslint-disable */
export const PRODUCTS = [
    {id:1,name:'Xiaomi Redmi Note 13 Pro',brand:'Xiaomi',category:'Mobile & Gadgets',price:28999,stock:142,rating:4.6,status:'Active',description:'6.67" AMOLED, 200MP camera, 5000mAh battery.',sku:'XIAO-RN13P-001',minThreshold:20},
    {id:2,name:'Walton Primo H10',brand:'Walton',category:'Mobile & Gadgets',price:13500,stock:87,rating:4.2,status:'Active',description:'Budget smartphone with 6GB RAM and 128GB storage.',sku:'WALT-PH10-002',minThreshold:15},
    {id:3,name:'Samsung Galaxy A55',brand:'Samsung',category:'Mobile & Gadgets',price:42000,stock:54,rating:4.5,status:'Active',description:'Mid-range flagship with Exynos processor.',sku:'SAMS-GA55-003',minThreshold:12},
    {id:4,name:'Symphony Z45',brand:'Symphony',category:'Mobile & Gadgets',price:9990,stock:210,rating:3.9,status:'Active',description:'Entry level smartphone, great value.',sku:'SYMP-Z45-004',minThreshold:25},
    {id:5,name:'Walton WT-EX20 AC 1.5 Ton',brand:'Walton',category:'Electronics',price:52000,stock:23,rating:4.4,status:'Active',description:'Inverter split AC, energy efficient.',sku:'WALT-AC20-005',minThreshold:10},
    {id:6,name:'Vision 43" Smart TV',brand:'Vision Electronics',category:'Electronics',price:31500,stock:40,rating:4.3,status:'Active',description:'Full HD smart TV with built-in apps.',sku:'VISN-43TV-006',minThreshold:15},
    {id:7,name:'Minister Rice Cooker 1.8L',brand:'Minister',category:'Home & Living',price:2450,stock:305,rating:4.1,status:'Active',description:'Automatic keep-warm rice cooker.',sku:'MINI-RC18-007',minThreshold:30},
    {id:8,name:'Kiam Metal Deluxe Non-stick Pan',brand:'Kiam',category:'Home & Living',price:1290,stock:180,rating:4.0,status:'Draft',description:'Non-stick frying pan, 26cm.',sku:'KIAM-NSP26-008',minThreshold:20},
    {id:9,name:'Aarong Handloom Saree',brand:'Aarong',category:'Fashion',price:3800,stock:65,rating:4.8,status:'Active',description:'Handwoven cotton saree with traditional motifs.',sku:'AARG-HLSR-009',minThreshold:10},
    {id:10,name:'Yellow Denim Jacket',brand:'Yellow',category:'Fashion',price:2200,stock:90,rating:4.2,status:'Active',description:'Classic fit denim jacket, unisex.',sku:'YLOW-DNJK-010',minThreshold:15},
    {id:11,name:'Sara Lifestyle Kurti',brand:'Sara',category:'Fashion',price:1450,stock:130,rating:4.0,status:'Active',description:'Printed cotton kurti, all sizes.',sku:'SARA-KRTI-011',minThreshold:20},
    {id:12,name:'Fair & Lovely Glow Cream',brand:'Unilever',category:'Beauty & Personal Care',price:320,stock:500,rating:3.8,status:'Active',description:'Daily brightening face cream.',sku:'UNIL-FLGC-012',minThreshold:50},
    {id:13,name:'Pran Frooto 1L',brand:'Pran',category:'Groceries',price:120,stock:1200,rating:4.3,status:'Active',description:'Mango flavored fruit drink.',sku:'PRAN-FRT1L-013',minThreshold:100},
    {id:14,name:'ACI Pure Salt 1kg',brand:'ACI',category:'Groceries',price:42,stock:2000,rating:4.5,status:'Active',description:'Iodized cooking salt.',sku:'ACI-SALT1K-014',minThreshold:150},
    {id:15,name:'Runner Turag Bicycle',brand:'Runner',category:'Sports & Outdoor',price:10500,stock:0,rating:4.1,status:'Out of Stock',description:'Single speed city bicycle.',sku:'RUNR-TURG-015',minThreshold:8},
    {id:16,name:'Baby Moo Diaper Pack (L)',brand:'Baby Moo',category:'Baby & Kids',price:890,stock:260,rating:4.4,status:'Active',description:'Ultra-soft diapers, 40pcs pack.',sku:'BABM-DPRL-016',minThreshold:40},
  ];
export const BRANDS = [
    {name:'Walton',category:'Electronics',productsCount:214,status:'Active',joined:'2019',verified:true,trustScore:91,loves:38200,followers:41500,tagline:'Made in Bangladesh, Trusted Nationwide',dealsListed:5,address:'Walton Corporate HQ, Chandra, Gazipur',email:'support.bd@waltonbd.com',phone:'09666-701701',priceRange:'৳3,000 – ৳180,000',ageFocus:'18 – 60 Years',audience:'Households, Nationwide',services:['Nationwide Service Center','2 Year Warranty','EMI up to 12 Months'],tags:['#MadeInBD','#Appliances','#Trusted']},
    {name:'Xiaomi',category:'Mobile & Gadgets',productsCount:96,status:'Active',joined:'2020',verified:true,trustScore:88,loves:52100,followers:60300,tagline:'Innovation For Everyone',dealsListed:3,address:'Xiaomi BD Flagship, Bashundhara City, Dhaka',email:'support.bd@xiaomi.com',phone:'09612-110110',priceRange:'৳1,500 – ৳150,000',ageFocus:'16 – 45 Years',audience:'Tech Enthusiasts',services:['Official Warranty','Express Home Delivery'],tags:['#TechDeals','#SmartLiving']},
    {name:'Samsung',category:'Mobile & Gadgets',productsCount:158,status:'Active',joined:'2018',verified:true,trustScore:96,loves:50050,followers:50000,tagline:'Inspire the World, Create the Future',dealsListed:2,address:'Samsung Prestige Flagship Store, House 14, Road 11, Banani, Dhaka 1213',email:'support.bd@samsung.com',phone:'09612-300300',priceRange:'৳12,000 – ৳350,000',ageFocus:'18 – 55 Years',audience:'Unisex / All Demographics',services:['Official Brand Panel Warranty','Same Day Store Pickup','Home Delivery Inside Dhaka'],tags:['#Gamers','#CorporateOffices','#CreativePhotographers','#ModernHomes'],ratingOverall:4.3,ratings:{quality:4.4,value:4.1,trust:4.5,service:4.0,design:4.6},categoriesCount:8,creatorsCount:18,saved:8200,dealsFound:64,verifiedOrders:25000,views:1200000,trending:true},
    {name:'Symphony',category:'Mobile & Gadgets',productsCount:74,status:'Active',joined:'2019',verified:true,trustScore:79,loves:19400,followers:22800,tagline:'Smart Phone for Everyone',dealsListed:2,address:'Symphony House, Tejgaon, Dhaka',email:'care@symphony-mobile.com',phone:'09666-747474',priceRange:'৳4,000 – ৳35,000',ageFocus:'16 – 40 Years',audience:'Budget-conscious Buyers',services:['1 Year Warranty','Nationwide Service Points'],tags:['#BudgetPhones','#LocalBrand']},
    {name:'Vision Electronics',category:'Electronics',productsCount:62,status:'Active',joined:'2021',verified:false,trustScore:71,loves:8200,followers:9600,tagline:'Vision for a Better Home',dealsListed:1,address:'Vision Emporium, Gulshan Avenue, Dhaka',email:'support@visionelectronics.com',phone:'09678-234561',priceRange:'৳2,500 – ৳90,000',ageFocus:'20 – 55 Years',audience:'Home Owners',services:['1 Year Warranty'],tags:['#HomeAppliances']},
    {name:'Minister',category:'Home & Living',productsCount:45,status:'Active',joined:'2020',verified:false,trustScore:74,loves:6100,followers:7300,tagline:'Feel The Difference',dealsListed:1,address:'Minister Plaza, Mirpur Road, Dhaka',email:'support@ministerbd.com',phone:'09612-556677',priceRange:'৳3,500 – ৳120,000',ageFocus:'20 – 55 Years',audience:'Households',services:['1 Year Warranty','Home Delivery'],tags:['#HomeLiving']},
    {name:'Aarong',category:'Fashion',productsCount:320,status:'Active',joined:'2017',verified:true,trustScore:93,loves:64500,followers:71200,tagline:'Bringing Rural Craft to Urban Markets',dealsListed:4,address:'Aarong Craft Center, Tejgaon, Dhaka',email:'care@aarong.com',phone:'09666-770770',priceRange:'৳500 – ৳25,000',ageFocus:'18 – 60 Years',audience:'Fashion & Lifestyle Shoppers',services:['7 Day Exchange','Nationwide Delivery'],tags:['#Handicraft','#EthnicWear','#SustainableFashion']},
    {name:'Yellow',category:'Fashion',productsCount:180,status:'Active',joined:'2018',verified:true,trustScore:85,loves:33200,followers:37800,tagline:'Fashion That Speaks',dealsListed:3,address:'Yellow Flagship, Dhanmondi, Dhaka',email:'support@yellowclothing.com',phone:'09612-880880',priceRange:'৳600 – ৳12,000',ageFocus:'16 – 35 Years',audience:'Young Adults',services:['7 Day Exchange','Store Pickup'],tags:['#StreetStyle','#Trending']},
    {name:'Pran',category:'Groceries',productsCount:410,status:'Active',joined:'2016',verified:true,trustScore:89,loves:71200,followers:82500,tagline:'Taste the Tradition',dealsListed:6,address:'Pran-RFL Center, Kawran Bazar, Dhaka',email:'support@pranfoods.com',phone:'09666-991991',priceRange:'৳20 – ৳2,500',ageFocus:'All Ages',audience:'General Households',services:['Same Day Delivery','Bulk Order Discounts'],tags:['#Groceries','#DailyEssentials']},
    {name:'ACI',category:'Groceries',productsCount:260,status:'Active',joined:'2016',verified:true,trustScore:87,loves:48900,followers:55100,tagline:'Improving Quality of Life',dealsListed:4,address:'ACI Center, Tejgaon, Dhaka',email:'support@aci-bd.com',phone:'09612-445566',priceRange:'৳15 – ৳3,000',ageFocus:'All Ages',audience:'General Households',services:['Same Day Delivery','Quality Guarantee'],tags:['#Groceries','#Wellness']},
    {name:'Runner',category:'Sports & Outdoor',productsCount:38,status:'Pending',joined:'2022',verified:false,trustScore:58,loves:1900,followers:2400,tagline:'Built to Move',dealsListed:0,address:'Runner Motors Plaza, Uttara, Dhaka',email:'support@runnerbd.com',phone:'09678-112233',priceRange:'৳1,200 – ৳45,000',ageFocus:'18 – 40 Years',audience:'Sports Enthusiasts',services:['1 Year Warranty'],tags:['#Sports','#Outdoor']},
    {name:'Baby Moo',category:'Baby & Kids',productsCount:52,status:'Active',joined:'2021',verified:false,trustScore:76,loves:9800,followers:11200,tagline:'Gentle Care for Little Ones',dealsListed:2,address:'Baby Moo Store, Banani, Dhaka',email:'support@babymoo.com',phone:'09612-667788',priceRange:'৳150 – ৳6,500',ageFocus:'Parents, 0–5yr Kids',audience:'New Parents',services:['Easy Exchange','Home Delivery'],tags:['#BabyCare','#Parenting']},
  ];
export const CREATORS = [
    {name:'Tech Talks BD',platform:'YouTube',followers:482000,videos:312,status:'Active',
      role:'Creator & Product Researcher',handle:'@techtalksbd',location:'Dhaka, Bangladesh',verified:true,
      bio:'Senior Tech Analyst & Digital Product Researcher with 10+ years of experience analyzing electronic imports, consumer durables, and PC components in the Bangladesh market.',
      trustScore:4.9,deliveries:'240+ deliveries',ratings:{accuracy:4.9,depth:4.8,clarity:4.7,trust:4.9,value:4.6},
      reelsCount:3,blogsCount:2,reviewsCount:240,bestFor:'Tech',
      expertiseTopics:[{name:'Smartphones',count:'128 Guides'},{name:'Laptops',count:'96 Guides'},{name:'PC Components',count:'82 Guides'},{name:'Audio',count:'78 Guides'},{name:'Cameras',count:'64 Guides'},{name:'Gaming',count:'52 Guides'}],
      latestReviews:[{product:'Samsung Galaxy S24 Ultra',date:'May 5, 2025',rating:4.9},{product:'Sony WH-1000XM5 Headphones',date:'Apr 28, 2025',rating:4.8},{product:'Dell XPS 15 (2024)',date:'Apr 20, 2025',rating:4.7}],
      backgroundBio:'Senior Tech Analyst & Digital Product Researcher with 10+ years of experience analyzing electronic imports, consumer durables, and PC components in the Bangladesh market.',
      areasOfExpertise:'Smartphones, Laptops, Gadget Guides, Dhaka Tech Hubs',
      contentPlatforms:'YouTube, Facebook',
      brandPartners:['Samsung','Xiaomi','ASUS','Sony','Dell','Acer'],
      collabTypes:['Product Reviews','Brand Stories','Buying Guides','Tech Analysis','Comparisons','Live Sessions'],
      contactEmail:'farhan.outreach@choosify.bd',responseTime:'24 – 48 hours',preferredContact:'Email',
      communityReviews:[{name:'Tanvir Hossain',rating:5,text:"Farhan bhai's reviews are so detailed and honest. Always helps me make the right decision!",context:'Samsung Galaxy S24 Ultra Review'},{name:'Nusrat Jahan',rating:5,text:'The most reliable tech reviewer in Bangladesh. His buying guides are gold!',context:'Best Laptop Guide 2025'},{name:'Rashed Ahmed',rating:5,text:'Love how he explains everything in simple terms. Super helpful for beginners like me.',context:'PC Build Guide'}],
    },
    {name:'Fashionista Dhaka',platform:'Instagram',followers:210000,videos:890,status:'Active'},
    {name:'Gadget Guru',platform:'YouTube',followers:356000,videos:198,status:'Active'},
    {name:'BD Foodie',platform:'TikTok',followers:620000,videos:1240,status:'Active'},
    {name:'Home Hacks BD',platform:'YouTube',followers:128000,videos:145,status:'Pending'},
    {name:'Beauty By Nusrat',platform:'Instagram',followers:340000,videos:560,status:'Active'},
    {name:'Sports Nation',platform:'YouTube',followers:95000,videos:88,status:'Active'},
    {name:'Mom & Baby BD',platform:'TikTok',followers:178000,videos:402,status:'Active'},
    {name:'Auto Review BD',platform:'YouTube',followers:64000,videos:72,status:'Suspended'},
    {name:'Bookworm Dhaka',platform:'Instagram',followers:41000,videos:210,status:'Active'},
  ];
export const CATEGORIES = [
    {name:'Fashion & Lifestyle',count:2150,icon:'👕',slug:'fashion-lifestyle',type:'Fashion',visible:true,description:'Apparel, footwear, and everyday lifestyle essentials.',featuredBrand:'Aarong',featured:true,trending:false,editorsPick:false,popular:true,newlyAdded:false,subcategories:[{name:'Sarees & Ethnic Wear',count:420},{name:"Men's Fashion",count:610},{name:'Footwear',count:280}]},
    {name:'Jewelry & Accessories',count:640,icon:'💎',slug:'jewelry-accessories',type:'Fashion',visible:true,description:'Fine jewelry, watches, and fashion accessories.',featuredBrand:'Aarong',featured:false,trending:true,editorsPick:false,popular:false,newlyAdded:false,subcategories:[{name:'Necklaces',count:180},{name:'Watches',count:210}]},
    {name:'Mobile & Phones',count:980,icon:'📱',slug:'mobile-phones',type:'Electronics',visible:true,description:'Smartphones, feature phones, and mobile accessories.',featuredBrand:'Samsung',featured:true,trending:true,editorsPick:false,popular:true,newlyAdded:false,subcategories:[{name:'Smartphones',count:520},{name:'Mobile Accessories',count:460}]},
    {name:'Sporting & Playstation',count:410,icon:'🏏',slug:'sporting-playstation',type:'Sports',visible:true,description:'Sports gear, fitness equipment, and gaming consoles.',featuredBrand:'',featured:false,trending:false,editorsPick:false,popular:false,newlyAdded:true,subcategories:[{name:'Fitness Equipment',count:150},{name:'Consoles',count:90}]},
    {name:'Gaming & Entertainment',count:365,icon:'🎮',slug:'gaming-entertainment',type:'Electronics',visible:true,description:'Gaming peripherals, consoles, and entertainment devices.',featuredBrand:'',featured:false,trending:true,editorsPick:false,popular:false,newlyAdded:false,subcategories:[{name:'Controllers',count:110},{name:'Headsets',count:95}]},
    {name:'Food & Restaurants',count:3020,icon:'🍴',slug:'food-restaurants',type:'Grocery',visible:true,description:'Groceries, packaged food, and restaurant partnerships.',featuredBrand:'Pran',featured:true,trending:false,editorsPick:true,popular:true,newlyAdded:false,subcategories:[{name:'Packaged Food',count:1400},{name:'Beverages',count:620}]},
    {name:'Tech & Electronics',count:1240,icon:'🖥',slug:'tech-electronics',type:'Electronics',visible:true,description:'Laptops, PC components, and electronics accessories.',featuredBrand:'Walton',featured:true,trending:true,editorsPick:true,popular:true,newlyAdded:false,subcategories:[{name:'Laptops',count:340},{name:'PC Components',count:280},{name:'Audio',count:210}]},
    {name:'TV & Appliances',count:560,icon:'📺',slug:'tv-appliances',type:'Home & Living',visible:true,description:'Televisions, kitchen appliances, and home electronics.',featuredBrand:'Walton',featured:false,trending:false,editorsPick:false,popular:false,newlyAdded:true,subcategories:[{name:'Televisions',count:180},{name:'Kitchen Appliances',count:240}]},
    {name:'Home & Living',count:1340,icon:'🏠',slug:'home-living',type:'Home & Living',visible:true,description:'Furniture, decor, and home organization essentials.',featuredBrand:'Minister',featured:false,trending:false,editorsPick:true,popular:false,newlyAdded:false,subcategories:[{name:'Furniture',count:410},{name:'Decor',count:290}]},
    {name:'Baby & Maternity',count:560,icon:'👶',slug:'baby-maternity',type:'Kids',visible:true,description:'Baby care, maternity wear, and kids essentials.',featuredBrand:'Baby Moo',featured:false,trending:false,editorsPick:false,popular:false,newlyAdded:true,subcategories:[{name:'Diapers & Care',count:220},{name:'Maternity Wear',count:140}]},
  ];
export const ORDERS = [
    {id:'#CH-10234',customer:'Farhan Kamal',date:'2026-07-17',items:3,total:45900,payment:'Paid',fulfillment:'Shipped'},
    {id:'#CH-10233',customer:'Nusrat Jahan',date:'2026-07-17',items:1,total:890,payment:'Paid',fulfillment:'Processing'},
    {id:'#CH-10232',customer:'Tanvir Ahmed',date:'2026-07-16',items:2,total:13890,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-10231',customer:'Sadia Islam',date:'2026-07-16',items:4,total:6420,payment:'COD',fulfillment:'Processing'},
    {id:'#CH-10230',customer:'Rakib Hasan',date:'2026-07-15',items:1,total:42000,payment:'Paid',fulfillment:'Shipped'},
    {id:'#CH-10229',customer:'Mim Akter',date:'2026-07-15',items:2,total:3540,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-10228',customer:'Shafiul Islam',date:'2026-07-14',items:5,total:8760,payment:'COD',fulfillment:'Cancelled'},
    {id:'#CH-10227',customer:'Priya Das',date:'2026-07-14',items:1,total:28999,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-10226',customer:'Kamal Uddin',date:'2026-07-13',items:3,total:4680,payment:'Paid',fulfillment:'Shipped'},
    {id:'#CH-10225',customer:'Fatema Begum',date:'2026-07-13',items:2,total:2380,payment:'COD',fulfillment:'Processing'},
    {id:'#CH-10224',customer:'Arif Chowdhury',date:'2026-07-12',items:1,total:52000,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-10223',customer:'Lamia Nur',date:'2026-07-12',items:6,total:9450,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-10222',customer:'Imran Hossain',date:'2026-07-11',items:2,total:1780,payment:'COD',fulfillment:'Delivered'},
    {id:'#CH-10221',customer:'Sanjida Khan',date:'2026-07-11',items:1,total:3800,payment:'Paid',fulfillment:'Refunded'},
    {id:'#CH-10220',customer:'Nayeem Islam',date:'2026-07-10',items:3,total:15600,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-90101',customer:'Sifat Rahman',date:'2026-07-12',items:1,total:4200,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-90098',customer:'Sifat Rahman',date:'2026-06-02',items:1,total:3600,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-90112',customer:'Nadia Islam',date:'2026-06-28',items:1,total:12400,payment:'Paid',fulfillment:'Delivered'},
    {id:'#CH-90121',customer:'Mahmudul Karim',date:'2026-07-15',items:1,total:2100,payment:'COD',fulfillment:'Processing'},
    {id:'#CH-90045',customer:'Rezaul Bari',date:'2026-02-03',items:1,total:900,payment:'COD',fulfillment:'Cancelled'},
    {id:'#CH-90040',customer:'Rezaul Bari',date:'2026-01-20',items:1,total:4300,payment:'Paid',fulfillment:'Delivered'},
  ];
export const DEALS = [
    {title:'Eid Mega Sale',brand:'Multiple',discount:'40%',starts:'2026-06-01',ends:'2026-07-15',status:'Expired'},
    {title:'Monsoon Electronics Fest',brand:'Walton',discount:'25%',starts:'2026-07-10',ends:'2026-07-25',status:'Active'},
    {title:'Mobile Mania',brand:'Xiaomi',discount:'15%',starts:'2026-07-05',ends:'2026-07-20',status:'Active'},
    {title:'Fashion Week Flash',brand:'Aarong',discount:'30%',starts:'2026-08-01',ends:'2026-08-07',status:'Scheduled'},
    {title:'Grocery Weekend',brand:'Pran / ACI',discount:'10%',starts:'2026-07-17',ends:'2026-07-19',status:'Active'},
    {title:'Back to School',brand:'Multiple',discount:'20%',starts:'2026-08-15',ends:'2026-08-31',status:'Scheduled'},
    {title:'Beauty Bonanza',brand:'Unilever',discount:'35%',starts:'2026-07-01',ends:'2026-07-14',status:'Expired'},
    {title:'Baby Care Week',brand:'Baby Moo',discount:'18%',starts:'2026-07-20',ends:'2026-07-27',status:'Active'},
    {title:'Sports Gear Sale',brand:'Runner',discount:'22%',starts:'2026-07-12',ends:'2026-07-22',status:'Active'},
    {title:'Home Living Discount',brand:'Minister / Kiam',discount:'15%',starts:'2026-07-16',ends:'2026-07-30',status:'Active'},
    {title:'Symphony Monsoon Combo Offer',brand:'Symphony',discount:'20%',starts:'2026-08-01',ends:'2026-08-10',status:'Pending Review',requestedBy:'Symphony (Seller)'},
    {title:'Yellow End of Season Clearance',brand:'Yellow',discount:'50%',starts:'2026-08-05',ends:'2026-08-15',status:'Pending Review',requestedBy:'Yellow (Seller)'},
  ];
export const REVIEW_QUEUE = [
    {id:1, reviewer:'Mehedi Rahman', sku:'Samsung Galaxy S25 Ultra', merchant:'TechZone BD', rating:1, status:'Flagged', reportCount:4,
      text:'"This phone is absolute garbage. The seller is a cheat and scammer. I will make everyone knows this shop is a fraud. Complete waste of money and time..."',
      aiScore:25, aiNote:'Contains abusive vocabulary and highly repetitive fraud accusations.', tags:['PERSONAL THREATS','ABUSIVE LANGUAGE']},
    {id:2, reviewer:'Anonymous K.', sku:'Walton 2-Door Fridge', merchant:'ElectroBD', rating:1, status:'Flagged', reportCount:2,
      text:'"Amazing product! Buy from this link: [bit.ly/xyz] for best price! This seller is the best. Everyone should buy here. [Affiliate link spam suspected]"',
      aiScore:10, aiNote:'Detected shortened external hyperlink [bit.ly] indicating commercial click hijacking.', tags:['EXTERNAL LINKS','SUSPECTED SPAM']},
    {id:3, reviewer:'Rifat Hasan', sku:'Aarong Jamdani Saree', merchant:'Aarong Digital', rating:3, status:'Published', reportCount:0,
      text:'"Fabric quality is good but delivery took 5 days longer than promised. The color was slightly different but acceptable. Would buy again."',
      aiScore:98, aiNote:'Balanced tone, specific criticism matching logistics delays. High authenticity index.', tags:[]},
    {id:4, reviewer:'Sultana Ahmed', sku:'Aarong Silk Panjabi', merchant:'Aarong Digital', rating:5, status:'Published', reportCount:0,
      text:'"Absolutely stunning design and pure silk fabric!!! Highly recommended and great customer service from the store representative!"',
      aiScore:92, aiNote:'Organic sentence structure, verified buyer credentials verified.', tags:[]},
    {id:5, reviewer:'Hasan Al-Amin', sku:'Apex Mens Formal Leather', merchant:'Apex Shoes', rating:1, status:'Pending', reportCount:1,
      text:'CHEAP CHEAP CHEAP!!! BUY HERE INSTEAD OF THAT OTHER BRAND!!! http://spam-store.info/apex-shoes super fast shipment, discount code: BIGPROMO',
      aiScore:15, aiNote:'Aggressive block capitals, external links, promotional coupon advertisement.', tags:['SUSPECTED SPAM']},
  ];
export const GENERIC_PAGES = {
    courierProviders: {title:'Courier Providers', subtitle:'Manage integrated delivery partners', columns:[{key:'name',label:'Provider'},{key:'coverage',label:'Coverage'},{key:'avgTime',label:'Avg. Delivery'},{key:'rate',label:'Base Rate'},{key:'status',label:'Status'}], rows:[
      {name:'Pathao Courier',coverage:'Nationwide',avgTime:'1-2 days',rate:'৳60',status:'Active'},
      {name:'Steadfast',coverage:'Nationwide',avgTime:'2-3 days',rate:'৳50',status:'Active'},
      {name:'RedX',coverage:'Major cities',avgTime:'1-2 days',rate:'৳65',status:'Active'},
      {name:'Sundarban Courier',coverage:'Nationwide',avgTime:'3-4 days',rate:'৳45',status:'Pending'},
      {name:'eCourier',coverage:'Dhaka only',avgTime:'Same day',rate:'৳80',status:'Active'},
    ]},
    shipmentConsole: {title:'Shipment Console', subtitle:'Active shipments across all couriers', columns:[{key:'id',label:'Shipment'},{key:'order',label:'Order'},{key:'courier',label:'Courier'},{key:'destination',label:'Destination'},{key:'status',label:'Status'}], rows:[
      {id:'#SH-88231',order:'#CH-10234',courier:'Pathao',destination:'Gulshan, Dhaka',status:'In Transit'},
      {id:'#SH-88230',order:'#CH-10232',courier:'RedX',destination:'Chattogram',status:'Delivered'},
      {id:'#SH-88229',order:'#CH-10230',courier:'Steadfast',destination:'Sylhet',status:'In Transit'},
      {id:'#SH-88228',order:'#CH-10227',courier:'Pathao',destination:'Uttara, Dhaka',status:'Delivered'},
      {id:'#SH-88227',order:'#CH-10224',courier:'eCourier',destination:'Dhanmondi, Dhaka',status:'Out for Delivery'},
      {id:'#SH-88226',order:'#CH-10221',courier:'Steadfast',destination:'Mirpur, Dhaka',status:'Pending Pickup'},
      {id:'#SH-88225',order:'#CH-10219',courier:'RedX',destination:'Khulna',status:'Failed Delivery'},
    ]},
    trackingCenter: {title:'Tracking Center', subtitle:'Real-time tracking status across all in-flight orders', columns:[{key:'id',label:'Tracking No.'},{key:'courier',label:'Courier'},{key:'lastUpdate',label:'Last Update'},{key:'location',label:'Location'},{key:'status',label:'Status'}], rows:[
      {id:'PTH99213',courier:'Pathao',lastUpdate:'2h ago',location:'Dhaka Sorting Hub',status:'In Transit'},
      {id:'RDX44120',courier:'RedX',lastUpdate:'5h ago',location:'Chattogram Depot',status:'Delivered'},
      {id:'STF77302',courier:'Steadfast',lastUpdate:'1h ago',location:'Sylhet Hub',status:'In Transit'},
      {id:'ECR20911',courier:'eCourier',lastUpdate:'20m ago',location:'Dhanmondi',status:'Out for Delivery'},
    ]},
    shippingLabels: {title:'Shipping Labels', subtitle:'Generate and manage printable courier labels', columns:[{key:'order',label:'Order'},{key:'courier',label:'Courier'},{key:'generated',label:'Generated'},{key:'weight',label:'Weight'},{key:'status',label:'Status'}], rows:[
      {order:'#CH-10234',courier:'Pathao',generated:'2026-07-17',weight:'0.8kg',status:'Printed'},
      {order:'#CH-10233',courier:'Steadfast',generated:'2026-07-17',weight:'0.3kg',status:'Pending'},
      {order:'#CH-10231',courier:'RedX',generated:'2026-07-16',weight:'1.4kg',status:'Printed'},
      {order:'#CH-10229',courier:'Pathao',generated:'2026-07-15',weight:'0.5kg',status:'Printed'},
    ]},
    courierAnalytics: {title:'Courier Analytics', subtitle:'Delivery performance by courier partner', columns:[{key:'courier',label:'Courier'},{key:'onTime',label:'On-Time %'},{key:'avgCost',label:'Avg. Cost'},{key:'volume',label:'Monthly Volume'},{key:'status',label:'Rating'}], rows:[
      {courier:'Pathao',onTime:'94%',avgCost:'৳62',volume:'8,240',status:'Excellent'},
      {courier:'Steadfast',onTime:'88%',avgCost:'৳51',volume:'6,120',status:'Good'},
      {courier:'RedX',onTime:'91%',avgCost:'৳67',volume:'4,830',status:'Excellent'},
      {courier:'Sundarban Courier',onTime:'76%',avgCost:'৳44',volume:'2,140',status:'Fair'},
    ]},
    moderationCenter: {title:'Moderation Center', subtitle:'Flagged content awaiting review', columns:[{key:'type',label:'Type'},{key:'content',label:'Content'},{key:'reportedBy',label:'Reported By'},{key:'reason',label:'Reason'},{key:'status',label:'Status'}], rows:[
      {type:'Review',content:'"Arrived with a scratch..."',reportedBy:'Auto-filter',reason:'Suspected fake',status:'Open'},
      {type:'Post',content:'Flash Sale Teaser',reportedBy:'User report',reason:'Misleading claim',status:'Resolved'},
      {type:'Listing',content:'Turag Bicycle (2nd unit)',reportedBy:'Seller report',reason:'Duplicate listing',status:'Open'},
      {type:'Message',content:'Buyer-seller thread #4021',reportedBy:'Auto-filter',reason:'Spam link',status:'Resolved'},
    ]},
    disputes: {title:'Disputes', subtitle:'Buyer/seller disputes requiring resolution', columns:[{key:'id',label:'Dispute'},{key:'parties',label:'Parties'},{key:'issue',label:'Issue'},{key:'opened',label:'Opened'},{key:'status',label:'Status'}], rows:[
      {id:'#DP-3391',parties:'Shafiul Islam vs. Runner',issue:'Item not as described',opened:'2026-07-14',status:'Open'},
      {id:'#DP-3390',parties:'Sanjida Khan vs. Aarong',issue:'Refund delay',opened:'2026-07-12',status:'Resolved'},
      {id:'#DP-3389',parties:'Kamal Uddin vs. Yellow',issue:'Wrong item shipped',opened:'2026-07-10',status:'Open'},
    ]},
    trustCenter: {title:'Trust Center', subtitle:'Platform-wide trust & safety signals', columns:[{key:'metric',label:'Metric'},{key:'value',label:'Value'},{key:'trend',label:'Trend'},{key:'status',label:'Status'}], rows:[
      {metric:'Verified Sellers',value:'1,842',trend:'▲ 4.2%',status:'Healthy'},
      {metric:'Fraud Reports (30d)',value:'23',trend:'▼ 11%',status:'Healthy'},
      {metric:'Fake Review Flags',value:'67',trend:'▲ 8%',status:'Watch'},
      {metric:'Counterfeit Reports',value:'5',trend:'0%',status:'Healthy'},
    ]},
    analytics: {title:'Analytics', subtitle:'Platform-wide traffic and engagement', columns:[{key:'metric',label:'Metric'},{key:'value',label:'Value'},{key:'status',label:'Change'}], rows:[
      {metric:'Site Visitors (30d)',value:'1.2M',status:'▲ 9.4%'},
      {metric:'Product Page Views',value:'4.6M',status:'▲ 6.1%'},
      {metric:'Search Queries',value:'820K',status:'▲ 14.2%'},
      {metric:'Compare Tool Usage',value:'96K',status:'▲ 21.8%'},
      {metric:'Avg. Session Duration',value:'4m 12s',status:'▼ 1.3%'},
    ]},
    finance: {title:'Finance', subtitle:'Platform-wide financial overview', columns:[{key:'metric',label:'Metric'},{key:'value',label:'Value'},{key:'status',label:'Change'}], rows:[
      {metric:'Gross Merchandise Value',value:'৳48.2M',status:'▲ 11.6%'},
      {metric:'Platform Commission',value:'৳3.9M',status:'▲ 9.8%'},
      {metric:'Payouts Pending',value:'৳2.1M',status:'0%'},
      {metric:'Refunds Issued',value:'৳412K',status:'▼ 4.2%'},
    ]},
    adminManagement: {title:'Admin Management', subtitle:'Manage admin accounts and access', columns:[{key:'name',label:'Admin'},{key:'email',label:'Email'},{key:'role',label:'Role'},{key:'lastActive',label:'Last Active'},{key:'status',label:'Status'}], rows:[
      {name:'Admin User',email:'admin@choosify.com',role:'Super Admin',lastActive:'Now',status:'Active'},
      {name:'Farzana Rahman',email:'farzana.r@choosify.com',role:'Content Admin',lastActive:'2h ago',status:'Active'},
      {name:'Shakib Al Noor',email:'shakib.n@choosify.com',role:'Support Admin',lastActive:'1d ago',status:'Active'},
      {name:'Ripon Das',email:'ripon.d@choosify.com',role:'Finance Admin',lastActive:'5d ago',status:'Suspended'},
    ]},
    verificationCenter: {title:'Verification Center', subtitle:'Seller & brand identity verification queue', columns:[{key:'name',label:'Applicant'},{key:'type',label:'Type'},{key:'submitted',label:'Submitted'},{key:'status',label:'Status'}], rows:[
      {name:'Doreen Fashions',type:'Seller',submitted:'2026-07-16',status:'Pending'},
      {name:'Nitol Motors',type:'Brand',submitted:'2026-07-14',status:'Approved'},
      {name:'Epyllion Group',type:'Seller',submitted:'2026-07-12',status:'Pending'},
      {name:'Square Toiletries',type:'Brand',submitted:'2026-07-08',status:'Rejected'},
    ]},
    subscriptionPlans: {title:'Subscription Plans', subtitle:'Seller & brand subscription tiers', columns:[{key:'plan',label:'Plan'},{key:'price',label:'Price'},{key:'subscribers',label:'Subscribers'},{key:'status',label:'Status'}], rows:[
      {plan:'Starter Seller',price:'৳999/mo',subscribers:842,status:'Active'},
      {plan:'Growth Seller',price:'৳2,499/mo',subscribers:310,status:'Active'},
      {plan:'Brand Partner',price:'৳9,999/mo',subscribers:64,status:'Active'},
      {plan:'Enterprise',price:'Custom',subscribers:12,status:'Active'},
    ]},
    monetizationCenter: {title:'Monetization Center', subtitle:'Ad placements and promoted listings', columns:[{key:'campaign',label:'Campaign'},{key:'brand',label:'Brand'},{key:'spend',label:'Spend'},{key:'impressions',label:'Impressions'},{key:'status',label:'Status'}], rows:[
      {campaign:'Homepage Hero Takeover',brand:'Xiaomi',spend:'৳180,000',impressions:'2.4M',status:'Active'},
      {campaign:'Search Boost',brand:'Walton',spend:'৳64,000',impressions:'980K',status:'Active'},
      {campaign:'Category Spotlight',brand:'Aarong',spend:'৳42,000',impressions:'610K',status:'Ended'},
    ]},
  };
